#!/usr/bin/env python3
"""Writes docs/protocol-vectors.json, the fixed inputs and expected HMAC that
every implementation of the identify signature must reproduce byte for byte,
and firmware/main/vectors.h, the same values for the firmware's SELFTEST.
Deterministic: the key and nonce are counting byte patterns, not random.

    scripts/gen-vectors.py          # rewrite both files
    scripts/gen-vectors.py --check  # exit 1 if either file is stale
"""
import hashlib
import hmac
import json
import pathlib
import sys

KEY = bytes(range(32))             # 000102...1f
NONCE = bytes(range(0xA0, 0xB0))   # a0a1...af
SLOT = 3

material = f"IDENTIFY|{NONCE.hex()}|{SLOT}"
mac = hmac.new(KEY, material.encode(), hashlib.sha256).hexdigest()

vectors = {
    "device_key": KEY.hex(),
    "nonce": NONCE.hex(),
    "slot": SLOT,
    "material": material,
    "mac": mac,
}
root = pathlib.Path(__file__).resolve().parents[1]
key_bytes = ", ".join(f"0x{b:02x}" for b in KEY)
outputs = {
    root / "docs" / "protocol-vectors.json": json.dumps(vectors, indent=2) + "\n",
    root / "firmware" / "main" / "vectors.h": f"""#pragma once
// Generated by scripts/gen-vectors.py from docs/protocol-vectors.json. Do not edit.
#include <stdint.h>

static const uint8_t VECTOR_DEVICE_KEY[32] = {{{key_bytes}}};
static const char VECTOR_NONCE[] = "{NONCE.hex()}";
static const uint16_t VECTOR_SLOT = {SLOT};
static const char VECTOR_MAC[] = "{mac}";
""",
}

stale = False
for path, text in outputs.items():
    if "--check" in sys.argv:
        if (path.read_text() if path.exists() else "") != text:
            print(f"{path} is stale; run scripts/gen-vectors.py", file=sys.stderr)
            stale = True
        else:
            print(f"{path} is current")
    else:
        path.write_text(text)
        print(f"wrote {path}")
sys.exit(1 if stale else 0)
